# Mini Dockerfile — 跳过 build 阶段(服务器内存 1.8G 必 OOM)
# 本机 pnpm build 出 dist 后,这个 Dockerfile 只打 nginx + dist
FROM --platform=linux/amd64 nginx:alpine
COPY dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
